ingestion:
  image: thoughtworksturkey/marketwatcher-data-ingestion-service
  environment:
    - KAFKA_CONNECTION_STRING=${KAFKA_CONNECTION_STRING}
    - twitterConsumerKey=${TWITTER_CONSUMER_KEY}
    - twitterConsumerSecret=${TWITTER_CONSUMER_SECRET}
    - twitterAccessToken=${TWITTER_ACCESS_TOKEN}
    - twitterAccessTokenSecret=${TWITTER_ACCESS_TOKEN_SECRET}
  ports:
    - "10700:10700"